#!/usr/bin/env bash

#拷贝邮件地址

dir=$HOME/.local/bin/python-tools

"${dir}"/mail-helper copy-address

#osascript -e "display notification \"拷贝邮件地址成功\" with title \"hotkeys\" sound name \"Glass\""

#传递消息给hammerspoon
echo "cmd v"
