#!/usr/bin/env bash

#拷贝邮件正文

dir=$HOME/.local/bin/python-tools

"${dir}"/mail-helper copy-lines

#osascript -e "display notification \"拷贝邮件正文成功\" with title \"hotkeys\" sound name \"Glass\""

#传递消息给hammerspoon
echo "cmd v+enter"
